[server]
hostname = "api.am.wso2.com"
node_ip = "127.0.0.1"
server_role = "api-publisher"
base_path = "${carbon.protocol}://${carbon.host}:${carbon.management.port}"

[user_store]
type = "database_unique_id"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.apim_db]
type = "mysql"
url = "jdbc:mysql://mysql:3306/WSO2AM_DB?autoReconnect=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://mysql:3306/WSO2AM_SHARED_DB?autoReconnect=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"

[[apim.gateway.environment]]
name= "Production and Sandbox"
type= "hybrid"
display_in_api_console= true
description= "This is a hybrid gateway that handles both production and sandbox token traffic."
service_url= "https://gateway:9443/services/"
username= "${admin.username}"
password= "${admin.password}"
ws_endpoint= "ws://api.gw.wso2.com:9099"
https_endpoint = "https://api.gateway.wso2.com"
show_as_token_endpoint_url = true

#[apim.analytics]
#store_api_url = "https://analytics.wso2.com:7444"
#username= "$ref{super_admin.username}"
#password= "$ref{super_admin.password}"
#
#[[apim.analytics.analytics_node]]
#analytics_url="tcp://analytic1.local:7612"
#analytics_auth_url="ssl://analytic1.local:7712"
#
#[[apim.analytics.analytics_node]]
#analytics_url="tcp://analytic2.local:7612"
#analytics_auth_url="ssl://analytic2.local:7712"

# Traffic Manager configurations
[apim.throttling]
service_url = "https://traffic-manager:9443/services/"
username= "$ref{super_admin.username}"
password= "$ref{super_admin.password}"

[[apim.throttling.url_group]]
traffic_manager_urls=["tcp://traffic-manager:9611"]
traffic_manager_auth_urls=["ssl://traffic-manager:9711"]

[apim.cache.scopes]
enable = true

[apim.cache.publisher_roles] #check the usage and move to dev role
enable = true

[apim.devportal]
url = "https://api.am.wso2.com:443/devportal"

[apim.workflow]
enable = false
service_url = "https://localhost:9445/bpmn"
username = "$ref{super_admin.username}"
password = "$ref{super_admin.password}"
callback_endpoint = "https://localhost:9443/api/am/publisher/v0.16/workflows/update-workflow-status"
token_endpoint = "https://localhost:8243/token"
client_registration_endpoint = "https://localhost:9443/client-registration/v0.16/register"
client_registration_username = "$ref{super_admin.username}"
client_registration_password = "$ref{super_admin.password}"

[transport.https.properties]
proxyPort = 443

[apim.event_hub]
event_listening_endpoints = ["tcp://traffic-manager:5672"]

[[apim.event_hub.publish.url_group]]
urls = ["tcp://traffic-manager:9611"]
auth_urls = ["ssl://traffic-manager:9711"]

# key manager implementation
[apim.key_manager]
service_url = "https://key-manager:9443/services/"
username= "$ref{super_admin.username}"
password= "$ref{super_admin.password}"
type = "WSO2-IS"

[apim.cache_invalidation]
enabled = true
domain = "publisher-domain"

[apim.sync_runtime_artifacts.publisher]
artifact_saver = "DBSaver"
publish_directly_to_gateway = false