[server]
hostname = "api.am.wso2.com"
node_ip = "127.0.0.1"
server_role="control-plane"
base_path = "${carbon.protocol}://${carbon.host}:${carbon.management.port}"
[user_store]
type = "database_unique_id"

[super_admin]
username = "admin@wso2.com"
password = "admin123"
create_admin_account = true

[tenant_mgt]
enable_email_domain= true

[database.apim_db]
type = "mysql"
url = "jdbc:mysql://mysql:3306/WSO2AM_DB?autoReconnect=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://mysql:3306/WSO2AM_SHARED_DB?autoReconnect=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"


[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"

[[apim.gateway.environment]]
name= "us-east-1"
type= "hybrid"
display_in_api_console = true
description= "This is a hybrid gateway that handles both production and sandbox token traffic."
service_url= "https://gateway:9443/services/"
username= "${admin.username}"
password= "${admin.password}"
ws_endpoint= "ws://api.gateway.wso2.com:9099"
https_endpoint = "https://api.gateway.wso2.com"



[apim.cache.recent_apis]
enable = false

[apim.cache.scopes]
enable = true

[apim.cache.tags]
expiry_time = 120000

[apim.oauth_config]
revoke_endpoint = "https://apim:9443/oauth2/revoke"
enable_token_encryption = false
enable_token_hashing = false

[apim.devportal]
url = "https://api.am.wso2.com/devportal"
enable_application_sharing = true
application_sharing_type = "default" #changed to type, saml, default
#application_sharing_impl = "org.wso2.carbon.apimgt.impl.DefaultGroupIDExtractorImpl"
display_multiple_versions = false
display_deprecated_apis = false
enable_comments = true
enable_ratings = true
enable_forum = true

[[event_handler]]
name="userPostSelfRegistration"
subscriptions=["POST_ADD_USER"]

[transport.https.properties]
proxyPort = 443

# Event Hub configurations
[apim.event_hub]
enable = true
username = "admin@wso2.com@carbon.super"
password = "$ref{super_admin.password}"
service_url = "https://apim:9443/services/"
event_listening_endpoints = ["tcp://apim:5672"]

[apim.event_hub.jms]
username = "admin!wso2.com!carbon.super"
password = "admin123"

[[apim.event_hub.publish.url_group]]
urls = ["tcp://apim:9611"]
auth_urls = ["ssl://apim:9711"]


# key manager implementation
[apim.key_manager]
service_url = "https://apim:9443/services/"
username= "$ref{super_admin.username}"
password= "$ref{super_admin.password}"
type = "default"

[apim.cache_invalidation]
enabled = true
domain = "devportal-domain"

[[event_listener]]
id = "token_revocation"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "org.wso2.is.notification.ApimOauthEventInterceptor"
order = 1
[event_listener.properties]
notification_endpoint = "https://apim:9443/internal/data/v1/notify"
username = "admin@wso2.com@carbon.super"
password = "${admin.password}"
'header.X-WSO2-KEY-MANAGER' = "default"